### ISSUE TITLE
Need to be able to access existing ModelDataPairs

### ISSUE THREAD

**Issue by helenginn** [mulch-environment/mulch#12]
I would like to be able to access existing ModelDataPair entries in Collection please!

i.e. a getter function like `Collection::modelDataPair(int i)` which will give me the i'th `ModelDataPair` object to play with

**Comment by virginia4** [comment]
I have made some changes, added a function in Collection (virtual, implementation in PCollection) called getMDP(int index). It works, but it needs for the _chds vector to be initialise, otherwise _chds is empty. I need to find a way to return the last called vector, if it how we are going to use it?
